### ISSUE TITLE
Websites coming back as None 

### ISSUE THREAD

**Issue by iHaagcom** [emojipeach/webpagestatuscheck#1]
* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [16/Mar/2022 12:56:45] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2022 12:56:45] "GET /static/stylesheet.css HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2022 12:56:45] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [16/Mar/2022 12:56:48] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2022 12:56:49] "GET /static/stylesheet.css HTTP/1.1" 304 -

![image](https://user-images.githubusercontent.com/24706243/158502194-d69ea184-b443-4ba0-8408-b2abf1534c29.png)

**Comment by shoaib-fixes** [comment]
Can't reproduce.
