### ISSUE TITLE
request module belongs to markupsafe now

### ISSUE THREAD

**Issue by JuanRamirezJorda** [emojipeach/webpagestatuscheck#2]
requirements.txt:

Flask
markupsafe

app.py:

import requests
import json
import threading
from socket import gaierror, gethostbyname
from multiprocessing.dummy import Pool as ThreadPool
from urllib.parse import urlparse
from flask import Flask, render_template, request, jsonify
from time import gmtime, strftime
from markupsafe  import escape

**Comment by shoaib-fixes** [comment]
Fixed, thanks.
